// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Shodan.FSharp")>]
[<assembly: AssemblyProductAttribute("Shodan.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("A Shodan API client for F#.")>]
[<assembly: AssemblyVersionAttribute("0.0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.0.2")>]
[<assembly: GuidAttribute("cc90107d-7c65-4dcb-bc13-bb3e0d75933f")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Shodan.FSharp"
    let [<Literal>] AssemblyProduct = "Shodan.FSharp"
    let [<Literal>] AssemblyDescription = "A Shodan API client for F#."
    let [<Literal>] AssemblyVersion = "0.0.2"
    let [<Literal>] AssemblyFileVersion = "0.0.2"
    let [<Literal>] Guid = "cc90107d-7c65-4dcb-bc13-bb3e0d75933f"
